pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = "zmusic-mod"

include("zmusic-core")
include(
        "zmusic-neoforge",
        "zmusic-neoforge:zmusic-neoforge-1.20.4",
        "zmusic-neoforge:zmusic-neoforge-1.20.6",
        "zmusic-neoforge:zmusic-neoforge-1.21.1"
)
