modLoader = "javafml"
loaderVersion = "[43,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/starhui-dev/amusic-mod/issues"
[[mods]]
modId = "amusic"
version = "${version}"
displayName = "AMusic"
logoFile = "icon.png"
description = "${description}"
displayURL = ""
authors = "ZhenXin"
[[dependencies.amusic]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "CLIENT"
[[dependencies.amusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2]"
ordering = "NONE"
side = "CLIENT"
[[dependencies.amusic]]
modId = "cloth_config"
mandatory = true
versionRange = "[8.0,)"
ordering = "NONE"
side = "CLIENT"
